In [ ]:
!pip install langdetect transformers torch pandas

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 19.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.3)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.31.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 74.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 64.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.3 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 70.4 MB/s eta 0:00:00
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=2902d91f3e4a27d7ade8f14d7dfeef3aeaa49b05de8743b82126215f569f2770
  Stored in directory: /root/.cache/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built langdetect
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, langdetect, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed langdetect-1.0.9 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
import pandas as pd
import re
from langdetect import detect
from collections import Counter
from transformers import pipeline

In [ ]:
file_name = "[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links.csv"
df = pd.read_csv(file_name, encoding="utf-8")
# List of text columns to check (update based on your CSV's actual columns)
text_columns = [
    'General Comments',
    '1. Sectors and (sub-)uses',
    '2. Emissions in the end-of-life phase',
    '3. Emissions in the end-of-life phase',
    '4. Impacts on the recycling industry',
    '5. Proposed derogations',
    '6. Missing uses',
    '7. Potential derogations marked for reconsideration',
    '8. Other identified uses',
    '9. Degradation potential of specific PFAS sub-groups',
    '10. Analytical methods'
]
print("Columns in CSV:", df.columns.tolist())
print("\nFirst 5 rows:")
display(df.head())

Columns in CSV: ['Ref.', 'Type', 'Date', 'Content', 'Org. country', 'Org. type', 'Org. name', 'Company name confidential', 'attachment_author', 'General Comments', '1. Sectors and (sub-)uses', '2. Emissions in the end-of-life phase', '3. Emissions in the end-of-life phase', '4. Impacts on the recycling industry', '5. Proposed derogations', '6. Missing uses', '7. Potential derogations marked for reconsideration', '8. Other identified uses', '9. Degradation potential of specific PFAS sub-groups', '10. Analytical methods', 'source_document', 'attachments']

First 5 rows:

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,3. Emissions in the end-of-life phase,4. Impacts on the recycling industry,5. Proposed derogations,6. Missing uses,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,The European Chips Act wants to ensure that Eu...,NaN,NaN,NaN,NaN,NaN,Part_1.docx,NaN
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
3,3850,BehalfOfAnOrganisation,2023/03/23 2:10,Scope or restriction option analysis,Hungary,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Part_1.docx,NaN

## Attachement and confidential dummy variables

In [ ]:
def combine_text(row):
    return ' '.join(str(val).lower() for val in row[text_columns] if pd.notna(val) and val.strip())

df['combined_text'] = df.apply(combine_text, axis=1)

In [ ]:
def is_valid_url(url):
    if pd.isnull(url):
        return False
    pattern = r'^https?://.*'
    return bool(re.match(pattern, str(url)))

# Apply the function to the 'attachments' column
df['attachment_link_dummy'] = df['attachments'].apply(lambda x: 1 if is_valid_url(x) else 0)

# Define keywords indicating confidential references
confidential_keywords = ['confidential', 'redacted']

# Function to check for confidential references in text columns
def check_confidential(row):
    for col in text_columns:
        if pd.notnull(row[col]):
            for keyword in confidential_keywords:
                if re.search(keyword, str(row[col]), re.IGNORECASE):
                    # Check if attachments column is empty or invalid
                    if not is_valid_url(row['attachments']):
                        return 1
    return 0

# Apply the function to each row
df['confidential_info_dummy'] = df.apply(check_confidential, axis=1)

# Critical columns for sentiment analysis
critical_columns = [
    'General Comments',
    '1. Sectors and (sub-)uses',
    '5. Proposed derogations',
    '6. Missing uses',
    '7. Potential derogations marked for reconsideration'
]

def check_missing_key_info(row):
    # Step 1: Count empty critical columns
    empty_count = sum(
        pd.isna(row[col]) or str(row[col]).strip() == ''
        for col in critical_columns
    )

    # Step 2: Combine critical columns
    combined = ' '.join(
        str(val).strip()
        for val in row[critical_columns]
        if pd.notna(val) and str(val).strip()
    )

    # Step 3: Check text length
    char_count = len(combined)
    word_count = len(combined.split())

    # Step 4: Flag only if both conditions are met
    if empty_count > 2 and (char_count < 50 or word_count < 10):
        return 1  # Key info likely lost
    return 0  # No significant info loss

# Apply to DataFrame
df['missing_key_info'] = df.apply(check_missing_key_info, axis=1)

In [ ]:
# prompt: save this into a new csv with two dummy variable

import pandas as pd
# ... (Your existing code) ...

# Save the DataFrame to a new CSV file
df.to_csv('[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy.csv', index=False, encoding='utf-8')

In [ ]:
df

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments,combined_text,attachment_link_dummy,confidential_info_dummy,missing_key_info
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,technical textiles,1,0,1
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,scope of restriction:\nthe proposed restrictio...,0,0,0
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
3,3850,BehalfOfAnOrganisation,2023/03/23 2:10,Scope or restriction option analysis,Hungary,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,we are using fluoropolymers for seals petroleu...,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5637,9588,BehalfOfAnOrganisation,2023/09/25 23:50,Scope or restriction option analysis,Lithuania,Industry or trade association,The Association of Lithuanian Chemical Industr...,NaN,NaN,As a member of the European Chemical Council (...,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,as a member of the european chemical council (...,0,0,0
5638,9589,BehalfOfAnOrganisation,2023/09/25 23:52,Scope or restriction option analysis,Germany,Company,medac Gesellschaft für klinische Spezialpräpar...,NaN,v.bahr@medac.de,1. The German pharmaceutical company medac Ges...,...,NaN,NaN,NaN,NaN,Part_123.docx,https://www.industrydocuments.ucsf.edu/chemica...,1. the german pharmaceutical company medac ges...,1,0,0
5639,9590,BehalfOfAnOrganisation,2023/09/25 23:54,Scope or restriction option analysis,Belgium,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,- use sectors “transport” – sub-use coating an...,0,0,1
5640,9591,BehalfOfAnOrganisation,2023/09/25 23:57,Hazard or exposure,Switzerland,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,Please refer to confidential attachment,Please refer to confidential attachment,Part_123.docx,NaN,- lithium battery recycling please refer to co...,0,1,1
5641,9592,BehalfOfAnOrganisation,2023/09/25 23:59,Scope or restriction option analysis,Germany,Industry or trade association,Verband TEGEWA e.V.,NaN,NaN,Verband TEGEWA e. V. is an association represe...,...,We refer to the VCI and EURATEX contributions.,NaN,NaN,NaN,Part_123.docx,NaN,verband tegewa e. v. is an association represe...,0,0,0

In [ ]:
# prompt: save the 0-20 rows to a new df named (20EXAMPLES) ECHA Consultation Contributions_dummy

# Assuming 'df' is already defined as in your provided code.

# Create a new DataFrame containing the first 20 rows
df_20examples = df.head(21)

# Save the new DataFrame to a CSV file
df_20examples.to_csv('20EXAMPLES_ECHA_Consultation_Contributions_dummy.csv', index=False)

In [ ]:
import pandas as pd
file_name = "[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy.csv"
df_dummy = pd.read_csv(file_name, encoding="utf-8")

In [ ]:
# prompt: drop the duplicated rows only keep one validate row

# Drop duplicated rows based on 'combined_text' column, keeping the first occurrence
df_dummy = df_dummy.drop_duplicates(subset=['combined_text'], keep='first')

# Display the updated DataFrame
df_dummy

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments,combined_text,attachment_link_dummy,confidential_info_dummy,missing_key_info
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,technical textiles,1,0,1
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,scope of restriction:\nthe proposed restrictio...,0,0,0
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,we are using fluoropolymers for seals petroleu...,0,0,0
5,3852,Individual,2023/03/23 10:31,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,The proposed ban encompasses an inconceivable ...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,the proposed ban encompasses an inconceivable ...,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5637,9588,BehalfOfAnOrganisation,2023/09/25 23:50,Scope or restriction option analysis,Lithuania,Industry or trade association,The Association of Lithuanian Chemical Industr...,NaN,NaN,As a member of the European Chemical Council (...,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,as a member of the european chemical council (...,0,0,0
5638,9589,BehalfOfAnOrganisation,2023/09/25 23:52,Scope or restriction option analysis,Germany,Company,medac Gesellschaft für klinische Spezialpräpar...,NaN,v.bahr@medac.de,1. The German pharmaceutical company medac Ges...,...,NaN,NaN,NaN,NaN,Part_123.docx,https://www.industrydocuments.ucsf.edu/chemica...,1. the german pharmaceutical company medac ges...,1,0,0
5639,9590,BehalfOfAnOrganisation,2023/09/25 23:54,Scope or restriction option analysis,Belgium,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,- use sectors “transport” – sub-use coating an...,0,0,1
5640,9591,BehalfOfAnOrganisation,2023/09/25 23:57,Hazard or exposure,Switzerland,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,Please refer to confidential attachment,Please refer to confidential attachment,Part_123.docx,NaN,- lithium battery recycling please refer to co...,0,1,1
5641,9592,BehalfOfAnOrganisation,2023/09/25 23:59,Scope or restriction option analysis,Germany,Industry or trade association,Verband TEGEWA e.V.,NaN,NaN,Verband TEGEWA e. V. is an association represe...,...,We refer to the VCI and EURATEX contributions.,NaN,NaN,NaN,Part_123.docx,NaN,verband tegewa e. v. is an association represe...,0,0,0

In [ ]:
# prompt: save df_dummy to [PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy_noduplicate.csv

# Save the DataFrame to a new CSV file
df_dummy.to_csv('[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy_noduplicate.csv', index=False, encoding='utf-8')