In [ ]:
!pip install langdetect transformers torch pandas

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 19.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.3)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.31.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 74.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 64.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.3 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 70.4 MB/s eta 0:00:00
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=2902d91f3e4a27d7ade8f14d7dfeef3aeaa49b05de8743b82126215f569f2770
  Stored in directory: /root/.cache/pip/wheels/0a/f2/b2/e5ca405801e05eb7c8ed5b3b4bcf1fcabcd6272c167640072e
Successfully built langdetect
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, langdetect, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed langdetect-1.0.9 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
import pandas as pd
import re
from langdetect import detect
from collections import Counter
from transformers import pipeline

In [ ]:
file_name = "[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links.csv"
df = pd.read_csv(file_name, encoding="utf-8")
# List of text columns to check (update based on your CSV's actual columns)
text_columns = [
    'General Comments',
    '1. Sectors and (sub-)uses',
    '2. Emissions in the end-of-life phase',
    '3. Emissions in the end-of-life phase',
    '4. Impacts on the recycling industry',
    '5. Proposed derogations',
    '6. Missing uses',
    '7. Potential derogations marked for reconsideration',
    '8. Other identified uses',
    '9. Degradation potential of specific PFAS sub-groups',
    '10. Analytical methods'
]
print("Columns in CSV:", df.columns.tolist())
print("\nFirst 5 rows:")
display(df.head())

Columns in CSV: ['Ref.', 'Type', 'Date', 'Content', 'Org. country', 'Org. type', 'Org. name', 'Company name confidential', 'attachment_author', 'General Comments', '1. Sectors and (sub-)uses', '2. Emissions in the end-of-life phase', '3. Emissions in the end-of-life phase', '4. Impacts on the recycling industry', '5. Proposed derogations', '6. Missing uses', '7. Potential derogations marked for reconsideration', '8. Other identified uses', '9. Degradation potential of specific PFAS sub-groups', '10. Analytical methods', 'source_document', 'attachments']

First 5 rows:

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,3. Emissions in the end-of-life phase,4. Impacts on the recycling industry,5. Proposed derogations,6. Missing uses,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,The European Chips Act wants to ensure that Eu...,NaN,NaN,NaN,NaN,NaN,Part_1.docx,NaN
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
3,3850,BehalfOfAnOrganisation,2023/03/23 2:10,Scope or restriction option analysis,Hungary,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Part_1.docx,NaN

In [ ]:
# Detect languages

# Function to detect language of first non-empty text column in a row
def get_row_language(row):
    for col in text_columns:
        text = row[col]
        if pd.notnull(text) and str(text).strip() != "":  # Skip empty or NaN
            try:
                return detect(str(text))
            except:
                continue  # Skip errors and try next column
    return 'unknown'  # If all text columns are empty

# Apply to each row
df['language'] = df.apply(get_row_language, axis=1)

# Count frequencies
language_counts = Counter(df['language'])
print("Language Frequencies:", language_counts)

Language Frequencies: Counter({'en': 4206, 'sv': 744, 'unknown': 333, 'de': 166, 'it': 49, 'ca': 24, 'fr': 23, 'no': 21, 'nl': 11, 'ja': 9, 'pt': 9, 'es': 8, 'so': 8, 'ro': 6, 'tl': 5, 'ko': 3, 'tr': 2, 'pl': 2, 'sq': 2, 'af': 2, 'fi': 2, 'et': 2, 'cs': 2, 'sk': 1, 'sw': 1, 'da': 1})

In [ ]:
language_to_model = {
    'en': None,  # 英文无需翻译
    'sv': 'Helsinki-NLP/opus-mt-sv-en',
    'de': 'Helsinki-NLP/opus-mt-de-en',
    'it': 'Helsinki-NLP/opus-mt-it-en',
    'ca': 'Helsinki-NLP/opus-mt-ca-en',
    'fr': 'Helsinki-NLP/opus-mt-fr-en',
    'no': 'Helsinki-NLP/opus-mt-no-en',
    'nl': 'Helsinki-NLP/opus-mt-nl-en',
    'pt': 'Helsinki-NLP/opus-mt-pt-en',
    'es': 'Helsinki-NLP/opus-mt-es-en',
    'ro': 'Helsinki-NLP/opus-mt-ro-en',
    'fi': 'Helsinki-NLP/opus-mt-fi-en',
    'cs': 'Helsinki-NLP/opus-mt-cs-en',
    'tr': 'Helsinki-NLP/opus-mt-tr-en',
    'da': 'Helsinki-NLP/opus-mt-da-en',
    'sk': 'Helsinki-NLP/opus-mt-sk-en',
    'ko': 'Helsinki-NLP/opus-mt-ko-en',
    'ja': 'Helsinki-NLP/opus-mt-ja-en',
    'pl': 'Helsinki-NLP/opus-mt-pl-en',
    'so': 'facebook/m2m100_418M',  # 索马里语
    'tl': 'facebook/m2m100_418M',  # 他加禄语
    'af': 'facebook/m2m100_418M',  # 南非荷兰语
    'sq': 'facebook/m2m100_418M',  # 阿尔巴尼亚语
    'et': 'facebook/m2m100_418M',  # 爱沙尼亚语
    'sw': 'facebook/m2m100_418M',  # 斯瓦希里语
    'unknown': None  # 未知语言
}

In [ ]:
from transformers import pipeline
import torch

# 检查 GPU 是否可用
device = 0 if torch.cuda.is_available() else -1  # 0 = GPU, -1 = CPU

# 预加载所有翻译模型（缓存）
model_cache = {}

def get_translator(src_lang):
    """
    根据源语言代码返回对应的翻译模型
    """
    # 如果语言不在支持列表或无需翻译，返回 None
    if src_lang not in language_to_model or language_to_model[src_lang] is None:
        return None

    model_name = language_to_model[src_lang]

    # 复用已缓存的模型
    if model_name in model_cache:
        return model_cache[model_name]

    # 加载新模型
    try:
        if 'm2m100' in model_name:
            # 多语言模型需指定源语言和目标语言
            translator = pipeline(
                "translation",
                model=model_name,
                device=device,
                src_lang=src_lang,
                tgt_lang='en'
            )
        else:
            translator = pipeline(
                "translation",
                model=model_name,
                device=device
            )
        model_cache[model_name] = translator
        return translator
    except Exception as e:
        print(f"Failed to load model for {src_lang}: {e}")
        return None

In [ ]:
def translate_text(text, src_lang='auto'):
    """
    翻译单个文本字段
    """
    if pd.isnull(text) or str(text).strip() == "":
        return text  # 跳过空值

    # 自动检测语言
    if src_lang == 'auto':
        src_lang = get_row_language(text)

    # 获取翻译器
    translator = get_translator(src_lang)
    if translator is None:
        return text  # 无法翻译时返回原文本

    # 分段翻译（防止超长文本）
    max_length = 400
    text_segments = [str(text)[i:i+max_length] for i in range(0, len(str(text)), max_length)]
    translated_segments = []

    for segment in text_segments:
        try:
            result = translator(segment, max_length=max_length, truncation=True)
            translated_segments.append(result[0]['translation_text'])
        except Exception as e:
            print(f"Translation error for segment '{segment}': {e}")
            translated_segments.append(segment)  # 翻译失败时保留原文本

    return " ".join(translated_segments)

# 对所有文本列应用翻译
for col in text_columns:
    df[f"{col}_en"] = df.apply(lambda row: translate_text(row[col], src_lang=row['language']), axis=1)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/307M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/307M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/840k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.56M [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/303M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/303M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/782k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.50M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/292M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/292M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/815k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/803k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/344M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/344M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/814k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/790k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.37M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/295M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/294M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/815k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/790k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/309M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/309M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/835k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/785k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.52M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/3.71M [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.14k [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/302M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/302M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/830k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/790k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.46M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/316M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/316M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/814k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/790k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.66M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/842k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/813k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.72M [00:00<?, ?B/s]

Device set to use cpu

model.safetensors:   0%|          | 0.00/312M [00:00<?, ?B/s]

Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/1.44k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/312M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/826k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

Device set to use cpu

config.json:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/832k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/790k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/307M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/307M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/830k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/789k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.60M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/300M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/300M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/820k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/788k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

Device set to use cpu

Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for ro: Helsinki-NLP/opus-mt-ro-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for no: Helsinki-NLP/opus-mt-no-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
Failed to load model for pt: Helsinki-NLP/opus-mt-pt-en is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
from transformers import pipeline
import torch

# Check if GPU is available
device = 0 if torch.cuda.is_available() else -1  # 0 = GPU, -1 = CPU

# Preload all required translation models
model_cache = {}

def get_translator(src_lang):
    if src_lang not in language_to_model or language_to_model[src_lang] is None:
        return None  # Skip translation

    model_name = language_to_model[src_lang]
    if model_name in model_cache:
        return model_cache[model_name]  # Reuse cached model

    translator = pipeline("translation", model=model_name, device=device)
    model_cache[model_name] = translator
    return translator

# Translate function with caching
def translate_text(text, src_lang='auto'):
    if pd.isnull(text) or str(text).strip() == "":
        return text

    # Detect language if not provided
    if src_lang == 'auto':
        src_lang = detect_language(text)

    translator = get_translator(src_lang)
    if translator is None:
        return text  # Return original if no model available

    # Split long texts into segments
    max_length = 400
    text_segments = [text[i:i+max_length] for i in range(0, len(text), max_length)]
    translated_segments = []

    for segment in text_segments:
        try:
            result = translator(segment, max_length=max_length, truncation=True)
            translated_segments.append(result[0]['translation_text'])
        except Exception as e:
            print(f"Translation error: {e}")
            translated_segments.append(segment)  # Fallback to original

    return " ".join(translated_segments)

## Attachement and confidential dummy variables

In [ ]:
def combine_text(row):
    return ' '.join(str(val).lower() for val in row[text_columns] if pd.notna(val) and val.strip())

df['combined_text'] = df.apply(combine_text, axis=1)

In [ ]:
def is_valid_url(url):
    if pd.isnull(url):
        return False
    pattern = r'^https?://.*'
    return bool(re.match(pattern, str(url)))

# Apply the function to the 'attachments' column
df['attachment_link_dummy'] = df['attachments'].apply(lambda x: 1 if is_valid_url(x) else 0)

# Define keywords indicating confidential references
confidential_keywords = ['confidential', 'redacted']

# Function to check for confidential references in text columns
def check_confidential(row):
    for col in text_columns:
        if pd.notnull(row[col]):
            for keyword in confidential_keywords:
                if re.search(keyword, str(row[col]), re.IGNORECASE):
                    # Check if attachments column is empty or invalid
                    if not is_valid_url(row['attachments']):
                        return 1
    return 0

# Apply the function to each row
df['confidential_info_dummy'] = df.apply(check_confidential, axis=1)

# Critical columns for sentiment analysis
critical_columns = [
    'General Comments',
    '1. Sectors and (sub-)uses',
    '5. Proposed derogations',
    '6. Missing uses',
    '7. Potential derogations marked for reconsideration'
]

def check_missing_key_info(row):
    # Step 1: Count empty critical columns
    empty_count = sum(
        pd.isna(row[col]) or str(row[col]).strip() == ''
        for col in critical_columns
    )

    # Step 2: Combine critical columns
    combined = ' '.join(
        str(val).strip()
        for val in row[critical_columns]
        if pd.notna(val) and str(val).strip()
    )

    # Step 3: Check text length
    char_count = len(combined)
    word_count = len(combined.split())

    # Step 4: Flag only if both conditions are met
    if empty_count > 2 and (char_count < 50 or word_count < 10):
        return 1  # Key info likely lost
    return 0  # No significant info loss

# Apply to DataFrame
df['missing_key_info'] = df.apply(check_missing_key_info, axis=1)

In [ ]:
# prompt: save this into a new csv with two dummy variable

import pandas as pd
# ... (Your existing code) ...

# Save the DataFrame to a new CSV file
df.to_csv('[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy.csv', index=False, encoding='utf-8')

In [ ]:
df

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments,combined_text,attachment_link_dummy,confidential_info_dummy,missing_key_info
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,technical textiles,1,0,1
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,scope of restriction:\nthe proposed restrictio...,0,0,0
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
3,3850,BehalfOfAnOrganisation,2023/03/23 2:10,Scope or restriction option analysis,Hungary,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,we are using fluoropolymers for seals petroleu...,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5637,9588,BehalfOfAnOrganisation,2023/09/25 23:50,Scope or restriction option analysis,Lithuania,Industry or trade association,The Association of Lithuanian Chemical Industr...,NaN,NaN,As a member of the European Chemical Council (...,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,as a member of the european chemical council (...,0,0,0
5638,9589,BehalfOfAnOrganisation,2023/09/25 23:52,Scope or restriction option analysis,Germany,Company,medac Gesellschaft für klinische Spezialpräpar...,NaN,v.bahr@medac.de,1. The German pharmaceutical company medac Ges...,...,NaN,NaN,NaN,NaN,Part_123.docx,https://www.industrydocuments.ucsf.edu/chemica...,1. the german pharmaceutical company medac ges...,1,0,0
5639,9590,BehalfOfAnOrganisation,2023/09/25 23:54,Scope or restriction option analysis,Belgium,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,- use sectors “transport” – sub-use coating an...,0,0,1
5640,9591,BehalfOfAnOrganisation,2023/09/25 23:57,Hazard or exposure,Switzerland,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,Please refer to confidential attachment,Please refer to confidential attachment,Part_123.docx,NaN,- lithium battery recycling please refer to co...,0,1,1
5641,9592,BehalfOfAnOrganisation,2023/09/25 23:59,Scope or restriction option analysis,Germany,Industry or trade association,Verband TEGEWA e.V.,NaN,NaN,Verband TEGEWA e. V. is an association represe...,...,We refer to the VCI and EURATEX contributions.,NaN,NaN,NaN,Part_123.docx,NaN,verband tegewa e. v. is an association represe...,0,0,0

In [ ]:
# prompt: save the 0-20 rows to a new df named (20EXAMPLES) ECHA Consultation Contributions_dummy

# Assuming 'df' is already defined as in your provided code.

# Create a new DataFrame containing the first 20 rows
df_20examples = df.head(21)

# Save the new DataFrame to a CSV file
df_20examples.to_csv('20EXAMPLES_ECHA_Consultation_Contributions_dummy.csv', index=False)

In [ ]:
import pandas as pd
file_name = "[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy.csv"
df_dummy = pd.read_csv(file_name, encoding="utf-8")

In [ ]:
# prompt: drop the duplicated rows only keep one validate row

# Drop duplicated rows based on 'combined_text' column, keeping the first occurrence
df_dummy = df_dummy.drop_duplicates(subset=['combined_text'], keep='first')

# Display the updated DataFrame
df_dummy

,Ref.,Type,Date,Content,Org. country,Org. type,Org. name,Company name confidential,attachment_author,General Comments,...,7. Potential derogations marked for reconsideration,8. Other identified uses,9. Degradation potential of specific PFAS sub-groups,10. Analytical methods,source_document,attachments,combined_text,attachment_link_dummy,confidential_info_dummy,missing_key_info
0,3834,BehalfOfAnOrganisation,2023/03/22 9:25,Scope or restriction option analysis,Germany,Company,Schreiner Group GmbH & Co. KG,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,technical textiles,1,0,1
1,3843,Individual,2023/03/22 18:20,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,Scope of restriction:\nThe proposed restrictio...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,scope of restriction:\nthe proposed restrictio...,0,0,0
2,3849,BehalfOfAnOrganisation,2023/03/23 1:45,Scope or restriction option analysis,Denmark,Company,<redacted>,Yes,SUOMELA Sanna,Please refer to the further outline in the att...,...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,We understand that an online information sessi...,Part_1.docx,https://www.industrydocuments.ucsf.edu/chemica...,please refer to the further outline in the att...,1,0,0
4,3851,BehalfOfAnOrganisation,2023/03/23 9:57,Request for exemption,Austria,Company,<redacted>,Yes,NaN,We are using fluoropolymers for seals,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,we are using fluoropolymers for seals petroleu...,0,0,0
5,3852,Individual,2023/03/23 10:31,Scope or restriction option analysis,NaN,NaN,NaN,NaN,NaN,The proposed ban encompasses an inconceivable ...,...,NaN,NaN,NaN,NaN,Part_1.docx,NaN,the proposed ban encompasses an inconceivable ...,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5637,9588,BehalfOfAnOrganisation,2023/09/25 23:50,Scope or restriction option analysis,Lithuania,Industry or trade association,The Association of Lithuanian Chemical Industr...,NaN,NaN,As a member of the European Chemical Council (...,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,as a member of the european chemical council (...,0,0,0
5638,9589,BehalfOfAnOrganisation,2023/09/25 23:52,Scope or restriction option analysis,Germany,Company,medac Gesellschaft für klinische Spezialpräpar...,NaN,v.bahr@medac.de,1. The German pharmaceutical company medac Ges...,...,NaN,NaN,NaN,NaN,Part_123.docx,https://www.industrydocuments.ucsf.edu/chemica...,1. the german pharmaceutical company medac ges...,1,0,0
5639,9590,BehalfOfAnOrganisation,2023/09/25 23:54,Scope or restriction option analysis,Belgium,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,NaN,NaN,Part_123.docx,NaN,- use sectors “transport” – sub-use coating an...,0,0,1
5640,9591,BehalfOfAnOrganisation,2023/09/25 23:57,Hazard or exposure,Switzerland,Company,<redacted>,Yes,NaN,-,...,NaN,NaN,Please refer to confidential attachment,Please refer to confidential attachment,Part_123.docx,NaN,- lithium battery recycling please refer to co...,0,1,1
5641,9592,BehalfOfAnOrganisation,2023/09/25 23:59,Scope or restriction option analysis,Germany,Industry or trade association,Verband TEGEWA e.V.,NaN,NaN,Verband TEGEWA e. V. is an association represe...,...,We refer to the VCI and EURATEX contributions.,NaN,NaN,NaN,Part_123.docx,NaN,verband tegewa e. v. is an association represe...,0,0,0

In [ ]:
# prompt: save df_dummy to [PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy_noduplicate.csv

# Save the DataFrame to a new CSV file
df_dummy.to_csv('[PUBLIC] ECHA Consultation Contributions - echa_comments_with_attachments_links_dummy_noduplicate.csv', index=False, encoding='utf-8')