# Language Detection with API

In [ ]:
#Upload files
from google.colab import drive
drive.mount('/content/drive')


INPUT_FILE = "/content/drive/MyDrive/file_name.csv"
OUTPUT_FILE = "/content/drive/MyDrive/file_name.csv"
CHECKPOINT_INTERVAL = 10

Mounted at /content/drive

In [ ]:
!pip install openai tqdm

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.77.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.9.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.13.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.0)

In [ ]:
import pandas as pd
import openai
from collections import Counter
import os
import time
from tqdm import tqdm

In [ ]:
client = openai.OpenAI(
    api_key="your_api_key_here",
    base_url="your_base_url_here"
)

In [ ]:
# LANGUAGE DETECTION
cols_to_check = ["General Comments"] + [
    f"Answer to specific info request {i}" for i in range(1, 11)
]


if os.path.exists(OUTPUT_FILE):
    df = pd.read_csv(OUTPUT_FILE)
    print(" Existing file found. Resuming from previous progress.")
else:
    df = pd.read_csv(INPUT_FILE)
    df["language"] = None

# Language detection function
def detect_language(text):
    if pd.isna(text) or not str(text).strip():
        return None

    prompt = f"""
Detect the language of this text and respond with only the 2-letter ISO 639-1 language code (e.g. en, de, fr, it).

Text:
\"{text.strip()}\"
"""
    try:
        response = client.chat.completions.create(
            model="gpt-35-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content.strip().lower()
    except Exception as e:
        print(f" Error at row {idx}: {e}")
        return None

# LOOP
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Detecting language"):
    if pd.notna(row["language"]):
        continue

    row_langs = []
    for col in cols_to_check:
        lang = detect_language(row[col])
        if lang:
            row_langs.append(lang)
        time.sleep(0.5)

    dominant_lang = Counter(row_langs).most_common(1)[0][0] if row_langs else None
    df.at[idx, "language"] = dominant_lang


    if idx % 5 == 0:
        df.to_csv(OUTPUT_FILE, index=False)
        print(f" Checkpoint saved at row {idx}")


df.to_csv(OUTPUT_FILE, index=False)
print(" Language detection complete and saved.")

# Translation with API

In [ ]:
# EXTRACT NON EN ROWS

# Load full dataset with language detection
df = pd.read_csv("/content/drive/MyDrive/file_language_detected.csv")


df_to_translate = df[df["language"] != "en"].copy()


df_to_translate.to_csv("/content/drive/MyDrive/file_to_translate.csv", index=False)
print(f"Step 2 complete: {len(df_to_translate)} rows saved for translation.")

✅ Step 2 complete: 1350 rows saved for translation.

In [ ]:
INPUT_TRANSLATE_FILE = "/content/drive/MyDrive/file_to_translate.csv"
OUTPUT_TRANSLATE_FILE = "/content/drive/MyDrive/file_translated_subset.csv"
CHECKPOINT_INTERVAL = 5


client = openai.OpenAI(
    api_key="your_api_key",
    base_url="your_base_url"
)

In [ ]:
# TRANSLATION
cols_to_translate = ["General Comments"] + [
    f"Answer to specific info request {i}" for i in range(1, 11)
]


if os.path.exists(OUTPUT_TRANSLATE_FILE):
    df = pd.read_csv(OUTPUT_TRANSLATE_FILE)
    print(" Resuming from previous checkpoint...")
else:
    df = pd.read_csv(INPUT_TRANSLATE_FILE)
    for col in cols_to_translate:
        df[f"{col}_translated"] = None
        df[f"{col}_translated"] = df[f"{col}_translated"].astype("string")

# Translation function with detected language
def translate_text(text, source_lang):
    if pd.isna(text) or not str(text).strip():
        return text

    prompt = f"""
The original language is {source_lang}. Translate the following text into English. Only return the translated text.

Text:
\"{text.strip()}\"
"""
    try:
        response = client.chat.completions.create(
            model="gpt-35-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f" Translation error: {e}")
        return text

# LOOP
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Translating rows"):
    if all(pd.notna(row[f"{col}_translated"]) for col in cols_to_translate):
        continue

    source_lang = row["language"]

    for col in cols_to_translate:
        if pd.isna(row[f"{col}_translated"]) and pd.notna(row[col]):
            df.at[idx, f"{col}_translated"] = translate_text(row[col], source_lang)
            time.sleep(0.5)

    if idx % CHECKPOINT_INTERVAL == 0:
        df.to_csv(OUTPUT_TRANSLATE_FILE, index=False)
        print(f"💾 Checkpoint saved at row {idx}")


df.to_csv(OUTPUT_TRANSLATE_FILE, index=False)
print(" Translation completed and saved.")

Translating rows:   0%|          | 1/1350 [00:01<43:51,  1.95s/it]

💾 Checkpoint saved at row 0

Translating rows:   0%|          | 3/1350 [00:03<21:15,  1.06it/s]

💾 Checkpoint saved at row 5

Translating rows:   1%|          | 11/1350 [00:09<19:10,  1.16it/s]

💾 Checkpoint saved at row 10

Translating rows:   1%|          | 16/1350 [00:14<19:25,  1.14it/s]

💾 Checkpoint saved at row 15

Translating rows:   2%|▏         | 21/1350 [00:58<4:37:37, 12.53s/it]

💾 Checkpoint saved at row 20

Translating rows:   2%|▏         | 26/1350 [01:16<1:44:47,  4.75s/it]

💾 Checkpoint saved at row 25

Translating rows:   2%|▏         | 31/1350 [01:47<1:28:34,  4.03s/it]

💾 Checkpoint saved at row 30

Translating rows:   3%|▎         | 36/1350 [01:52<36:05,  1.65s/it]

💾 Checkpoint saved at row 35

Translating rows:   3%|▎         | 41/1350 [01:57<25:23,  1.16s/it]

💾 Checkpoint saved at row 40

Translating rows:   3%|▎         | 46/1350 [02:03<24:18,  1.12s/it]

💾 Checkpoint saved at row 45

Translating rows:   4%|▍         | 51/1350 [02:08<23:10,  1.07s/it]

💾 Checkpoint saved at row 50

Translating rows:   4%|▍         | 56/1350 [02:15<26:05,  1.21s/it]

💾 Checkpoint saved at row 55

Translating rows:   5%|▍         | 61/1350 [02:21<27:33,  1.28s/it]

💾 Checkpoint saved at row 60

Translating rows:   5%|▍         | 66/1350 [02:28<27:26,  1.28s/it]

💾 Checkpoint saved at row 65

Translating rows:   5%|▌         | 71/1350 [02:33<25:09,  1.18s/it]

💾 Checkpoint saved at row 70

Translating rows:   6%|▌         | 76/1350 [02:39<26:44,  1.26s/it]

💾 Checkpoint saved at row 75

Translating rows:   6%|▌         | 81/1350 [02:45<26:56,  1.27s/it]

💾 Checkpoint saved at row 80

Translating rows:   6%|▋         | 86/1350 [02:51<23:21,  1.11s/it]

💾 Checkpoint saved at row 85

Translating rows:   7%|▋         | 91/1350 [02:57<27:21,  1.30s/it]

💾 Checkpoint saved at row 90

Translating rows:   7%|▋         | 96/1350 [03:03<28:18,  1.35s/it]

💾 Checkpoint saved at row 95

Translating rows:   7%|▋         | 101/1350 [03:09<24:35,  1.18s/it]

💾 Checkpoint saved at row 100

Translating rows:   8%|▊         | 106/1350 [03:14<19:51,  1.04it/s]

💾 Checkpoint saved at row 105

Translating rows:   8%|▊         | 111/1350 [03:21<27:25,  1.33s/it]

💾 Checkpoint saved at row 110

Translating rows:   9%|▊         | 116/1350 [03:27<25:49,  1.26s/it]

💾 Checkpoint saved at row 115

Translating rows:   9%|▉         | 121/1350 [03:32<20:31,  1.00s/it]

💾 Checkpoint saved at row 120

Translating rows:   9%|▉         | 126/1350 [03:39<29:24,  1.44s/it]

💾 Checkpoint saved at row 125

Translating rows:  10%|▉         | 131/1350 [03:43<20:50,  1.03s/it]

💾 Checkpoint saved at row 130

Translating rows:  10%|█         | 136/1350 [03:50<26:43,  1.32s/it]

💾 Checkpoint saved at row 135

Translating rows:  10%|█         | 141/1350 [03:58<25:39,  1.27s/it]

💾 Checkpoint saved at row 140

Translating rows:  11%|█         | 146/1350 [04:05<27:10,  1.35s/it]

💾 Checkpoint saved at row 145

Translating rows:  11%|█         | 151/1350 [04:11<23:32,  1.18s/it]

💾 Checkpoint saved at row 150

Translating rows:  12%|█▏        | 156/1350 [04:18<28:07,  1.41s/it]

💾 Checkpoint saved at row 155

Translating rows:  12%|█▏        | 161/1350 [04:24<25:02,  1.26s/it]

💾 Checkpoint saved at row 160

Translating rows:  12%|█▏        | 166/1350 [04:31<26:54,  1.36s/it]

💾 Checkpoint saved at row 165

Translating rows:  13%|█▎        | 171/1350 [04:37<23:22,  1.19s/it]

💾 Checkpoint saved at row 170

Translating rows:  13%|█▎        | 176/1350 [04:42<22:24,  1.15s/it]

💾 Checkpoint saved at row 175

Translating rows:  13%|█▎        | 181/1350 [04:46<16:43,  1.16it/s]

💾 Checkpoint saved at row 180

Translating rows:  14%|█▍        | 186/1350 [04:52<19:11,  1.01it/s]

💾 Checkpoint saved at row 185

Translating rows:  14%|█▍        | 191/1350 [04:58<23:50,  1.23s/it]

💾 Checkpoint saved at row 190

Translating rows:  15%|█▍        | 196/1350 [05:03<21:19,  1.11s/it]

💾 Checkpoint saved at row 195

Translating rows:  15%|█▍        | 201/1350 [05:10<24:54,  1.30s/it]

💾 Checkpoint saved at row 200

Translating rows:  15%|█▌        | 206/1350 [05:16<26:43,  1.40s/it]

💾 Checkpoint saved at row 205

Translating rows:  16%|█▌        | 211/1350 [05:32<59:09,  3.12s/it]

💾 Checkpoint saved at row 210

Translating rows:  16%|█▌        | 216/1350 [05:39<30:34,  1.62s/it]

💾 Checkpoint saved at row 215

Translating rows:  16%|█▋        | 221/1350 [05:45<24:20,  1.29s/it]

💾 Checkpoint saved at row 220

Translating rows:  17%|█▋        | 226/1350 [05:50<18:40,  1.00it/s]

💾 Checkpoint saved at row 225

Translating rows:  17%|█▋        | 231/1350 [05:56<21:11,  1.14s/it]

💾 Checkpoint saved at row 230

Translating rows:  17%|█▋        | 236/1350 [06:02<21:32,  1.16s/it]

💾 Checkpoint saved at row 235

Translating rows:  18%|█▊        | 241/1350 [06:12<29:43,  1.61s/it]

💾 Checkpoint saved at row 240

Translating rows:  18%|█▊        | 246/1350 [06:18<20:53,  1.14s/it]

💾 Checkpoint saved at row 245

Translating rows:  19%|█▊        | 251/1350 [06:25<26:39,  1.46s/it]

💾 Checkpoint saved at row 250

Translating rows:  19%|█▉        | 256/1350 [06:31<26:38,  1.46s/it]

💾 Checkpoint saved at row 255

Translating rows:  19%|█▉        | 261/1350 [06:37<21:59,  1.21s/it]

💾 Checkpoint saved at row 260

Translating rows:  20%|█▉        | 266/1350 [06:43<20:38,  1.14s/it]

💾 Checkpoint saved at row 265

Translating rows:  20%|██        | 271/1350 [06:49<21:58,  1.22s/it]

💾 Checkpoint saved at row 270

Translating rows:  20%|██        | 276/1350 [06:54<21:08,  1.18s/it]

💾 Checkpoint saved at row 275

Translating rows:  21%|██        | 281/1350 [07:00<22:19,  1.25s/it]

💾 Checkpoint saved at row 280

Translating rows:  21%|██        | 286/1350 [07:07<24:01,  1.36s/it]

💾 Checkpoint saved at row 285

Translating rows:  22%|██▏       | 291/1350 [07:14<24:46,  1.40s/it]

💾 Checkpoint saved at row 290

Translating rows:  22%|██▏       | 296/1350 [07:19<19:23,  1.10s/it]

💾 Checkpoint saved at row 295

Translating rows:  22%|██▏       | 301/1350 [07:34<36:54,  2.11s/it]

💾 Checkpoint saved at row 300

Translating rows:  23%|██▎       | 306/1350 [07:42<27:31,  1.58s/it]

💾 Checkpoint saved at row 305

Translating rows:  23%|██▎       | 311/1350 [07:49<27:40,  1.60s/it]

💾 Checkpoint saved at row 310

Translating rows:  23%|██▎       | 316/1350 [07:55<20:20,  1.18s/it]

💾 Checkpoint saved at row 315

Translating rows:  24%|██▍       | 321/1350 [08:01<24:40,  1.44s/it]

💾 Checkpoint saved at row 320

Translating rows:  24%|██▍       | 326/1350 [08:07<18:12,  1.07s/it]

💾 Checkpoint saved at row 325

Translating rows:  25%|██▍       | 331/1350 [08:13<18:57,  1.12s/it]

💾 Checkpoint saved at row 330

Translating rows:  25%|██▍       | 336/1350 [08:17<17:12,  1.02s/it]

💾 Checkpoint saved at row 335

Translating rows:  25%|██▌       | 341/1350 [08:22<17:50,  1.06s/it]

💾 Checkpoint saved at row 340

Translating rows:  26%|██▌       | 346/1350 [08:28<22:12,  1.33s/it]

💾 Checkpoint saved at row 345

Translating rows:  26%|██▌       | 351/1350 [08:37<22:39,  1.36s/it]

💾 Checkpoint saved at row 350

Translating rows:  26%|██▋       | 356/1350 [08:45<34:06,  2.06s/it]

💾 Checkpoint saved at row 355

Translating rows:  27%|██▋       | 361/1350 [08:51<24:21,  1.48s/it]

💾 Checkpoint saved at row 360

Translating rows:  27%|██▋       | 366/1350 [08:58<21:04,  1.29s/it]

💾 Checkpoint saved at row 365

Translating rows:  27%|██▋       | 371/1350 [09:04<19:52,  1.22s/it]

💾 Checkpoint saved at row 370

Translating rows:  28%|██▊       | 376/1350 [09:10<17:58,  1.11s/it]

💾 Checkpoint saved at row 375

Translating rows:  28%|██▊       | 381/1350 [09:16<20:12,  1.25s/it]

💾 Checkpoint saved at row 380

Translating rows:  29%|██▊       | 386/1350 [09:23<20:41,  1.29s/it]

💾 Checkpoint saved at row 385

Translating rows:  29%|██▉       | 391/1350 [09:30<22:00,  1.38s/it]

💾 Checkpoint saved at row 390

Translating rows:  29%|██▉       | 396/1350 [09:37<19:16,  1.21s/it]

💾 Checkpoint saved at row 395

Translating rows:  30%|██▉       | 401/1350 [09:45<33:37,  2.13s/it]

💾 Checkpoint saved at row 400

Translating rows:  30%|███       | 406/1350 [09:51<19:09,  1.22s/it]

💾 Checkpoint saved at row 405

Translating rows:  30%|███       | 411/1350 [09:58<20:26,  1.31s/it]

💾 Checkpoint saved at row 410

Translating rows:  31%|███       | 416/1350 [10:03<17:41,  1.14s/it]

💾 Checkpoint saved at row 415

Translating rows:  31%|███       | 421/1350 [10:09<18:35,  1.20s/it]

💾 Checkpoint saved at row 420

Translating rows:  32%|███▏      | 426/1350 [10:16<21:20,  1.39s/it]

💾 Checkpoint saved at row 425

Translating rows:  32%|███▏      | 431/1350 [10:22<18:18,  1.20s/it]

💾 Checkpoint saved at row 430

Translating rows:  32%|███▏      | 436/1350 [10:28<19:23,  1.27s/it]

💾 Checkpoint saved at row 435

Translating rows:  33%|███▎      | 441/1350 [10:34<18:56,  1.25s/it]

💾 Checkpoint saved at row 440

Translating rows:  33%|███▎      | 446/1350 [10:39<15:37,  1.04s/it]

💾 Checkpoint saved at row 445

Translating rows:  33%|███▎      | 451/1350 [10:45<17:56,  1.20s/it]

💾 Checkpoint saved at row 450

Translating rows:  34%|███▍      | 456/1350 [10:51<17:36,  1.18s/it]

💾 Checkpoint saved at row 455

Translating rows:  34%|███▍      | 461/1350 [10:56<18:05,  1.22s/it]

💾 Checkpoint saved at row 460

Translating rows:  35%|███▍      | 466/1350 [11:03<17:52,  1.21s/it]

💾 Checkpoint saved at row 465

Translating rows:  35%|███▍      | 471/1350 [11:08<16:20,  1.12s/it]

💾 Checkpoint saved at row 470

Translating rows:  35%|███▌      | 476/1350 [11:14<15:48,  1.09s/it]

💾 Checkpoint saved at row 475

Translating rows:  36%|███▌      | 481/1350 [11:21<21:30,  1.49s/it]

💾 Checkpoint saved at row 480

Translating rows:  36%|███▌      | 486/1350 [11:28<20:43,  1.44s/it]

💾 Checkpoint saved at row 485

Translating rows:  36%|███▋      | 491/1350 [11:34<18:09,  1.27s/it]

💾 Checkpoint saved at row 490

Translating rows:  37%|███▋      | 496/1350 [11:41<18:05,  1.27s/it]

💾 Checkpoint saved at row 495

Translating rows:  37%|███▋      | 501/1350 [11:48<18:07,  1.28s/it]

💾 Checkpoint saved at row 500

Translating rows:  37%|███▋      | 506/1350 [11:53<15:22,  1.09s/it]

💾 Checkpoint saved at row 505

Translating rows:  38%|███▊      | 511/1350 [12:00<19:15,  1.38s/it]

💾 Checkpoint saved at row 510

Translating rows:  38%|███▊      | 516/1350 [12:06<18:19,  1.32s/it]

💾 Checkpoint saved at row 515

Translating rows:  39%|███▊      | 521/1350 [12:14<20:02,  1.45s/it]

💾 Checkpoint saved at row 520

Translating rows:  39%|███▉      | 526/1350 [12:20<17:35,  1.28s/it]

💾 Checkpoint saved at row 525

Translating rows:  39%|███▉      | 531/1350 [12:27<15:39,  1.15s/it]

💾 Checkpoint saved at row 530

Translating rows:  40%|███▉      | 536/1350 [12:34<17:37,  1.30s/it]

💾 Checkpoint saved at row 535

Translating rows:  40%|████      | 541/1350 [12:42<25:10,  1.87s/it]

💾 Checkpoint saved at row 540

Translating rows:  40%|████      | 546/1350 [12:50<22:36,  1.69s/it]

💾 Checkpoint saved at row 545

Translating rows:  41%|████      | 551/1350 [12:56<16:45,  1.26s/it]

💾 Checkpoint saved at row 550

Translating rows:  41%|████      | 556/1350 [13:03<18:09,  1.37s/it]

💾 Checkpoint saved at row 555

Translating rows:  42%|████▏     | 561/1350 [13:08<16:19,  1.24s/it]

💾 Checkpoint saved at row 560

Translating rows:  42%|████▏     | 566/1350 [13:14<16:38,  1.27s/it]

💾 Checkpoint saved at row 565

Translating rows:  42%|████▏     | 571/1350 [13:20<16:36,  1.28s/it]

💾 Checkpoint saved at row 570

Translating rows:  43%|████▎     | 576/1350 [13:27<16:34,  1.29s/it]

💾 Checkpoint saved at row 575

Translating rows:  43%|████▎     | 581/1350 [13:32<14:48,  1.16s/it]

💾 Checkpoint saved at row 580

Translating rows:  43%|████▎     | 586/1350 [13:39<17:11,  1.35s/it]

💾 Checkpoint saved at row 585

Translating rows:  44%|████▍     | 591/1350 [13:45<15:44,  1.24s/it]

💾 Checkpoint saved at row 590

Translating rows:  44%|████▍     | 596/1350 [13:51<15:30,  1.23s/it]

💾 Checkpoint saved at row 595

Translating rows:  45%|████▍     | 601/1350 [14:00<19:38,  1.57s/it]

💾 Checkpoint saved at row 600

Translating rows:  45%|████▍     | 606/1350 [14:08<21:56,  1.77s/it]

💾 Checkpoint saved at row 605

Translating rows:  45%|████▌     | 611/1350 [14:13<13:51,  1.13s/it]

💾 Checkpoint saved at row 610

Translating rows:  46%|████▌     | 616/1350 [14:20<17:24,  1.42s/it]

💾 Checkpoint saved at row 615

Translating rows:  46%|████▌     | 621/1350 [14:30<20:37,  1.70s/it]

💾 Checkpoint saved at row 620

Translating rows:  46%|████▋     | 626/1350 [14:36<17:04,  1.41s/it]

💾 Checkpoint saved at row 625

Translating rows:  47%|████▋     | 631/1350 [14:41<13:21,  1.11s/it]

💾 Checkpoint saved at row 630

Translating rows:  47%|████▋     | 636/1350 [14:49<17:06,  1.44s/it]

💾 Checkpoint saved at row 635

Translating rows:  47%|████▋     | 641/1350 [14:55<14:19,  1.21s/it]

💾 Checkpoint saved at row 640

Translating rows:  48%|████▊     | 646/1350 [15:00<13:27,  1.15s/it]

💾 Checkpoint saved at row 645

Translating rows:  48%|████▊     | 651/1350 [15:07<18:12,  1.56s/it]

💾 Checkpoint saved at row 650

Translating rows:  49%|████▊     | 656/1350 [15:14<17:30,  1.51s/it]

💾 Checkpoint saved at row 655

Translating rows:  49%|████▉     | 661/1350 [15:21<14:17,  1.24s/it]

💾 Checkpoint saved at row 660

Translating rows:  49%|████▉     | 666/1350 [15:26<12:34,  1.10s/it]

💾 Checkpoint saved at row 665

Translating rows:  50%|████▉     | 671/1350 [15:32<13:46,  1.22s/it]

💾 Checkpoint saved at row 670

Translating rows:  50%|█████     | 676/1350 [15:38<13:26,  1.20s/it]

💾 Checkpoint saved at row 675

Translating rows:  50%|█████     | 681/1350 [15:44<13:26,  1.21s/it]

💾 Checkpoint saved at row 680

Translating rows:  51%|█████     | 686/1350 [15:51<16:17,  1.47s/it]

💾 Checkpoint saved at row 685

Translating rows:  51%|█████     | 691/1350 [15:58<15:18,  1.39s/it]

💾 Checkpoint saved at row 690

Translating rows:  52%|█████▏    | 696/1350 [16:03<13:14,  1.21s/it]

💾 Checkpoint saved at row 695

Translating rows:  52%|█████▏    | 701/1350 [16:10<14:57,  1.38s/it]

💾 Checkpoint saved at row 700

Translating rows:  52%|█████▏    | 706/1350 [16:18<17:56,  1.67s/it]

💾 Checkpoint saved at row 705

Translating rows:  53%|█████▎    | 711/1350 [16:25<16:07,  1.51s/it]

💾 Checkpoint saved at row 710

Translating rows:  53%|█████▎    | 716/1350 [16:32<14:42,  1.39s/it]

💾 Checkpoint saved at row 715

Translating rows:  53%|█████▎    | 721/1350 [16:39<16:39,  1.59s/it]

💾 Checkpoint saved at row 720

Translating rows:  54%|█████▍    | 726/1350 [16:45<13:24,  1.29s/it]

💾 Checkpoint saved at row 725

Translating rows:  54%|█████▍    | 731/1350 [16:52<14:56,  1.45s/it]

💾 Checkpoint saved at row 730

Translating rows:  55%|█████▍    | 736/1350 [16:59<13:33,  1.32s/it]

💾 Checkpoint saved at row 735

Translating rows:  55%|█████▍    | 741/1350 [17:04<10:53,  1.07s/it]

💾 Checkpoint saved at row 740

Translating rows:  55%|█████▌    | 746/1350 [17:11<13:35,  1.35s/it]

💾 Checkpoint saved at row 745

Translating rows:  56%|█████▌    | 751/1350 [17:18<14:17,  1.43s/it]

💾 Checkpoint saved at row 750

Translating rows:  56%|█████▌    | 756/1350 [17:25<12:25,  1.25s/it]

💾 Checkpoint saved at row 755

Translating rows:  56%|█████▋    | 761/1350 [17:31<13:23,  1.36s/it]

💾 Checkpoint saved at row 760

Translating rows:  57%|█████▋    | 766/1350 [17:42<24:19,  2.50s/it]

💾 Checkpoint saved at row 765

Translating rows:  57%|█████▋    | 771/1350 [17:50<17:39,  1.83s/it]

💾 Checkpoint saved at row 770

Translating rows:  57%|█████▋    | 776/1350 [17:57<14:19,  1.50s/it]

💾 Checkpoint saved at row 775

Translating rows:  58%|█████▊    | 781/1350 [18:03<11:31,  1.21s/it]

💾 Checkpoint saved at row 780

Translating rows:  58%|█████▊    | 786/1350 [18:10<13:09,  1.40s/it]

💾 Checkpoint saved at row 785

Translating rows:  59%|█████▊    | 791/1350 [18:17<12:09,  1.31s/it]

💾 Checkpoint saved at row 790

Translating rows:  59%|█████▉    | 796/1350 [18:34<30:43,  3.33s/it]

💾 Checkpoint saved at row 795

Translating rows:  59%|█████▉    | 801/1350 [18:40<14:44,  1.61s/it]

💾 Checkpoint saved at row 800

Translating rows:  60%|█████▉    | 806/1350 [18:51<16:55,  1.87s/it]

💾 Checkpoint saved at row 805

Translating rows:  60%|██████    | 811/1350 [18:59<16:12,  1.80s/it]

💾 Checkpoint saved at row 810

Translating rows:  60%|██████    | 816/1350 [19:06<12:26,  1.40s/it]

💾 Checkpoint saved at row 815

Translating rows:  61%|██████    | 821/1350 [19:11<10:31,  1.19s/it]

💾 Checkpoint saved at row 820

Translating rows:  61%|██████    | 826/1350 [19:16<08:07,  1.07it/s]

💾 Checkpoint saved at row 825

Translating rows:  62%|██████▏   | 831/1350 [19:23<10:56,  1.26s/it]

💾 Checkpoint saved at row 830

Translating rows:  62%|██████▏   | 836/1350 [19:31<12:57,  1.51s/it]

💾 Checkpoint saved at row 835

Translating rows:  62%|██████▏   | 841/1350 [19:38<11:43,  1.38s/it]

💾 Checkpoint saved at row 840

Translating rows:  63%|██████▎   | 846/1350 [19:45<12:36,  1.50s/it]

💾 Checkpoint saved at row 845

Translating rows:  63%|██████▎   | 851/1350 [19:51<09:52,  1.19s/it]

💾 Checkpoint saved at row 850

Translating rows:  63%|██████▎   | 856/1350 [19:57<10:05,  1.22s/it]

💾 Checkpoint saved at row 855

Translating rows:  64%|██████▍   | 861/1350 [20:03<09:50,  1.21s/it]

💾 Checkpoint saved at row 860

Translating rows:  64%|██████▍   | 866/1350 [20:19<18:40,  2.31s/it]

💾 Checkpoint saved at row 865

Translating rows:  65%|██████▍   | 871/1350 [20:28<13:32,  1.70s/it]

💾 Checkpoint saved at row 870

Translating rows:  65%|██████▍   | 876/1350 [20:53<41:40,  5.27s/it]

💾 Checkpoint saved at row 875

Translating rows:  65%|██████▌   | 881/1350 [21:00<16:18,  2.09s/it]

💾 Checkpoint saved at row 880

Translating rows:  66%|██████▌   | 886/1350 [21:07<11:04,  1.43s/it]

💾 Checkpoint saved at row 885

Translating rows:  66%|██████▌   | 891/1350 [21:13<09:14,  1.21s/it]

💾 Checkpoint saved at row 890

Translating rows:  66%|██████▋   | 896/1350 [21:27<18:07,  2.40s/it]

💾 Checkpoint saved at row 895

Translating rows:  67%|██████▋   | 901/1350 [21:35<12:56,  1.73s/it]

💾 Checkpoint saved at row 900

Translating rows:  67%|██████▋   | 906/1350 [21:59<39:59,  5.40s/it]

💾 Checkpoint saved at row 905

Translating rows:  67%|██████▋   | 911/1350 [22:08<17:07,  2.34s/it]

💾 Checkpoint saved at row 910

Translating rows:  68%|██████▊   | 916/1350 [22:15<09:48,  1.36s/it]

💾 Checkpoint saved at row 915

Translating rows:  68%|██████▊   | 921/1350 [22:26<14:40,  2.05s/it]

💾 Checkpoint saved at row 920

Translating rows:  69%|██████▊   | 926/1350 [22:40<19:51,  2.81s/it]

💾 Checkpoint saved at row 925

Translating rows:  69%|██████▉   | 931/1350 [22:47<11:12,  1.61s/it]

💾 Checkpoint saved at row 930

Translating rows:  69%|██████▉   | 936/1350 [22:51<06:23,  1.08it/s]

💾 Checkpoint saved at row 935

Translating rows:  70%|██████▉   | 941/1350 [22:58<07:25,  1.09s/it]

💾 Checkpoint saved at row 940

Translating rows:  70%|███████   | 946/1350 [23:15<15:59,  2.37s/it]

💾 Checkpoint saved at row 945

Translating rows:  70%|███████   | 951/1350 [23:22<09:16,  1.40s/it]

💾 Checkpoint saved at row 950

Translating rows:  71%|███████   | 956/1350 [23:31<09:30,  1.45s/it]

💾 Checkpoint saved at row 955

Translating rows:  71%|███████   | 961/1350 [24:08<32:57,  5.08s/it]

💾 Checkpoint saved at row 960

Translating rows:  72%|███████▏  | 966/1350 [24:28<29:37,  4.63s/it]

💾 Checkpoint saved at row 965

Translating rows:  72%|███████▏  | 971/1350 [24:37<12:27,  1.97s/it]

💾 Checkpoint saved at row 970

Translating rows:  72%|███████▏  | 976/1350 [24:41<06:39,  1.07s/it]

💾 Checkpoint saved at row 975

Translating rows:  73%|███████▎  | 981/1350 [25:03<13:18,  2.16s/it]

💾 Checkpoint saved at row 980

Translating rows:  73%|███████▎  | 986/1350 [25:07<06:43,  1.11s/it]

💾 Checkpoint saved at row 985

Translating rows:  73%|███████▎  | 991/1350 [25:12<06:55,  1.16s/it]

💾 Checkpoint saved at row 990

Translating rows:  74%|███████▍  | 996/1350 [25:17<05:36,  1.05it/s]

💾 Checkpoint saved at row 995

Translating rows:  74%|███████▍  | 1001/1350 [25:22<05:29,  1.06it/s]

💾 Checkpoint saved at row 1000

Translating rows:  75%|███████▍  | 1006/1350 [25:26<05:05,  1.13it/s]

💾 Checkpoint saved at row 1005

Translating rows:  75%|███████▍  | 1011/1350 [25:33<10:02,  1.78s/it]

💾 Checkpoint saved at row 1010

Translating rows:  75%|███████▌  | 1016/1350 [26:00<33:11,  5.96s/it]

💾 Checkpoint saved at row 1015

Translating rows:  76%|███████▌  | 1021/1350 [26:07<12:09,  2.22s/it]

💾 Checkpoint saved at row 1020

Translating rows:  76%|███████▌  | 1026/1350 [26:21<20:25,  3.78s/it]

💾 Checkpoint saved at row 1025

Translating rows:  76%|███████▋  | 1031/1350 [26:27<09:49,  1.85s/it]

💾 Checkpoint saved at row 1030

Translating rows:  77%|███████▋  | 1036/1350 [26:33<07:21,  1.40s/it]

💾 Checkpoint saved at row 1035

Translating rows:  77%|███████▋  | 1041/1350 [26:47<10:04,  1.96s/it]

💾 Checkpoint saved at row 1040

Translating rows:  77%|███████▋  | 1046/1350 [26:57<14:24,  2.84s/it]

💾 Checkpoint saved at row 1045

Translating rows:  78%|███████▊  | 1051/1350 [27:04<07:21,  1.48s/it]

💾 Checkpoint saved at row 1050

Translating rows:  78%|███████▊  | 1056/1350 [27:12<06:41,  1.37s/it]

💾 Checkpoint saved at row 1055

Translating rows:  79%|███████▊  | 1061/1350 [28:17<33:13,  6.90s/it]

💾 Checkpoint saved at row 1060

Translating rows:  79%|███████▉  | 1066/1350 [28:27<15:30,  3.28s/it]

💾 Checkpoint saved at row 1065

Translating rows:  79%|███████▉  | 1071/1350 [28:40<13:27,  2.90s/it]

💾 Checkpoint saved at row 1070

Translating rows:  80%|███████▉  | 1076/1350 [28:46<06:04,  1.33s/it]

💾 Checkpoint saved at row 1075

Translating rows:  80%|████████  | 1081/1350 [28:50<04:11,  1.07it/s]

💾 Checkpoint saved at row 1080

Translating rows:  80%|████████  | 1086/1350 [29:20<26:19,  5.98s/it]

💾 Checkpoint saved at row 1085

Translating rows:  81%|████████  | 1091/1350 [30:21<51:38, 11.96s/it]

💾 Checkpoint saved at row 1090

Translating rows:  81%|████████  | 1096/1350 [30:57<28:22,  6.70s/it]

💾 Checkpoint saved at row 1095

Translating rows:  82%|████████▏ | 1101/1350 [31:06<11:23,  2.74s/it]

💾 Checkpoint saved at row 1100

Translating rows:  82%|████████▏ | 1106/1350 [31:10<06:00,  1.48s/it]

💾 Checkpoint saved at row 1105

Translating rows:  82%|████████▏ | 1111/1350 [31:20<08:01,  2.01s/it]

💾 Checkpoint saved at row 1110

Translating rows:  83%|████████▎ | 1116/1350 [31:38<14:38,  3.75s/it]

💾 Checkpoint saved at row 1115

Translating rows:  83%|████████▎ | 1121/1350 [31:50<09:39,  2.53s/it]

💾 Checkpoint saved at row 1120

Translating rows:  83%|████████▎ | 1126/1350 [31:55<04:25,  1.19s/it]

💾 Checkpoint saved at row 1125

Translating rows:  84%|████████▍ | 1131/1350 [32:04<06:16,  1.72s/it]

💾 Checkpoint saved at row 1130

Translating rows:  84%|████████▍ | 1136/1350 [32:09<03:43,  1.04s/it]

💾 Checkpoint saved at row 1135

Translating rows:  85%|████████▍ | 1141/1350 [32:27<08:16,  2.37s/it]

💾 Checkpoint saved at row 1140

Translating rows:  85%|████████▍ | 1146/1350 [32:36<05:19,  1.57s/it]

💾 Checkpoint saved at row 1145

Translating rows:  85%|████████▌ | 1151/1350 [32:49<07:19,  2.21s/it]

💾 Checkpoint saved at row 1150

Translating rows:  86%|████████▌ | 1156/1350 [32:54<04:43,  1.46s/it]

💾 Checkpoint saved at row 1155

Translating rows:  86%|████████▌ | 1161/1350 [33:04<07:42,  2.45s/it]

💾 Checkpoint saved at row 1160

Translating rows:  86%|████████▋ | 1166/1350 [33:11<04:46,  1.56s/it]

💾 Checkpoint saved at row 1165

Translating rows:  87%|████████▋ | 1171/1350 [33:16<03:03,  1.02s/it]

💾 Checkpoint saved at row 1170

Translating rows:  87%|████████▋ | 1176/1350 [33:21<03:05,  1.07s/it]

💾 Checkpoint saved at row 1175

Translating rows:  87%|████████▋ | 1181/1350 [33:27<03:18,  1.17s/it]

💾 Checkpoint saved at row 1180

Translating rows:  88%|████████▊ | 1186/1350 [33:48<06:19,  2.32s/it]

💾 Checkpoint saved at row 1185

Translating rows:  88%|████████▊ | 1191/1350 [34:14<12:21,  4.66s/it]

💾 Checkpoint saved at row 1190

Translating rows:  89%|████████▊ | 1196/1350 [34:21<05:00,  1.95s/it]

💾 Checkpoint saved at row 1195

Translating rows:  89%|████████▉ | 1200/1350 [34:29<05:48,  2.32s/it]

💾 Checkpoint saved at row 1200

Translating rows:  89%|████████▉ | 1206/1350 [34:35<03:11,  1.33s/it]

💾 Checkpoint saved at row 1205

Translating rows:  90%|████████▉ | 1211/1350 [34:48<04:59,  2.16s/it]

💾 Checkpoint saved at row 1210

Translating rows:  90%|█████████ | 1216/1350 [35:00<07:29,  3.35s/it]

💾 Checkpoint saved at row 1215

Translating rows:  90%|█████████ | 1221/1350 [35:07<04:03,  1.89s/it]

💾 Checkpoint saved at row 1220

Translating rows:  91%|█████████ | 1226/1350 [35:21<05:43,  2.77s/it]

💾 Checkpoint saved at row 1225

Translating rows:  91%|█████████ | 1231/1350 [35:27<02:57,  1.49s/it]

💾 Checkpoint saved at row 1230

Translating rows:  92%|█████████▏| 1236/1350 [35:50<08:19,  4.38s/it]

💾 Checkpoint saved at row 1235

Translating rows:  92%|█████████▏| 1241/1350 [35:56<02:56,  1.62s/it]

💾 Checkpoint saved at row 1240

Translating rows:  92%|█████████▏| 1246/1350 [36:12<06:50,  3.95s/it]

💾 Checkpoint saved at row 1245

Translating rows:  93%|█████████▎| 1251/1350 [37:07<19:09, 11.61s/it]

💾 Checkpoint saved at row 1250

Translating rows:  93%|█████████▎| 1256/1350 [37:17<05:05,  3.25s/it]

💾 Checkpoint saved at row 1255

Translating rows:  93%|█████████▎| 1261/1350 [37:40<09:09,  6.17s/it]

💾 Checkpoint saved at row 1260

Translating rows:  94%|█████████▍| 1266/1350 [37:53<03:53,  2.78s/it]

💾 Checkpoint saved at row 1265

Translating rows:  94%|█████████▍| 1271/1350 [38:01<02:30,  1.90s/it]

💾 Checkpoint saved at row 1270

Translating rows:  94%|█████████▍| 1275/1350 [38:14<03:03,  2.44s/it]

💾 Checkpoint saved at row 1275

Translating rows:  95%|█████████▍| 1281/1350 [38:55<05:30,  4.79s/it]

💾 Checkpoint saved at row 1280

Translating rows:  95%|█████████▌| 1286/1350 [39:25<05:20,  5.00s/it]

💾 Checkpoint saved at row 1285

Translating rows:  96%|█████████▌| 1291/1350 [39:33<02:11,  2.22s/it]

💾 Checkpoint saved at row 1290

Translating rows:  96%|█████████▌| 1296/1350 [39:44<02:30,  2.78s/it]

💾 Checkpoint saved at row 1295

Translating rows:  96%|█████████▋| 1301/1350 [39:49<00:59,  1.22s/it]

💾 Checkpoint saved at row 1300

Translating rows:  97%|█████████▋| 1306/1350 [39:58<01:37,  2.21s/it]

💾 Checkpoint saved at row 1305

Translating rows:  97%|█████████▋| 1311/1350 [40:08<01:15,  1.94s/it]

💾 Checkpoint saved at row 1310

Translating rows:  97%|█████████▋| 1316/1350 [40:16<00:49,  1.46s/it]

💾 Checkpoint saved at row 1315

Translating rows:  98%|█████████▊| 1321/1350 [40:37<01:44,  3.62s/it]

💾 Checkpoint saved at row 1320

Translating rows:  98%|█████████▊| 1326/1350 [41:11<02:28,  6.17s/it]

💾 Checkpoint saved at row 1325

Translating rows:  99%|█████████▊| 1331/1350 [41:40<02:39,  8.38s/it]

💾 Checkpoint saved at row 1330

Translating rows:  99%|█████████▉| 1336/1350 [41:50<00:51,  3.71s/it]

💾 Checkpoint saved at row 1335

Translating rows:  99%|█████████▉| 1341/1350 [42:42<01:55, 12.79s/it]

💾 Checkpoint saved at row 1340

Translating rows: 100%|█████████▉| 1346/1350 [42:57<00:19,  4.86s/it]

💾 Checkpoint saved at row 1345

Translating rows: 100%|██████████| 1350/1350 [43:04<00:00,  1.91s/it]

✅ Translation completed and saved.

## Extra file cleaning and merging

### Cleaning

In [ ]:
# Save a column with ISO codes
import pandas as pd
import re


df = pd.read_csv("/content/drive/MyDrive/file_language_detected.csv")


def is_iso_639_1(lang):
    return bool(re.fullmatch(r"[a-z]{2}", str(lang).strip().lower()))


df_non_iso = df[~df["language"].apply(is_iso_639_1)].copy()


df_non_iso.to_csv("/content/drive/MyDrive/pfas_non_iso_languages.csv", index=False)
print(f" Subset saved: {len(df_non_iso)} rows with non-ISO languages.")

✅ Subset saved: 472 rows with non-ISO languages.

In [ ]:

full_file = "/content/drive/MyDrive/file_language_detected.csv"
corrections_file = "/content/drive/MyDrive/Copia di pfas_non_iso_languages.xlsx"
output_file = "/content/drive/MyDrive/pfas_comments_with_language_corrected.csv"


df_full = pd.read_csv(full_file)
df_corrections = pd.read_excel(corrections_file)


df_merged = df_full.merge(df_corrections, on="ID", how="left")


df_merged["language_corrected"] = df_merged["actual language"].combine_first(df_merged["language"])


df_merged.drop(columns=["actual language"], inplace=True)


df_merged.to_csv(output_file, index=False)
print(f" Done! Corrected file saved as: {output_file}")

✅ Done! Corrected file saved as: /content/drive/MyDrive/pfas_comments_with_language_corrected.csv

In [ ]:
import pandas as pd


full_file = "/content/drive/MyDrive/pfas_comments_with_language.csv"
corrections_file = "/content/drive/MyDrive/Copia di pfas_non_iso_languages.xlsx"
output_file = "/content/drive/MyDrive/pfas_comments_with_language_corrected.csv"


df_full = pd.read_csv(full_file)
df_corrections = pd.read_excel(corrections_file)


df_merged = df_full.merge(df_corrections, on="ID", how="left")
df_merged["language"] = df_merged["actual language"].combine_first(df_merged["language"])


df_merged.drop(columns=["actual language"], inplace=True)


df_merged.to_csv(output_file, index=False)
print(f"✅ Cleaned file saved to: {output_file}")

✅ Cleaned file saved to: /content/drive/MyDrive/pfas_comments_with_language_corrected.csv

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/pfas_comments_with_language_corrected.csv")


def is_iso_639_1(lang):
    return bool(re.fullmatch(r"[a-z]{2}", str(lang).strip().lower()))


df_non_iso = df[~df["language"].apply(is_iso_639_1)].copy()


df_non_iso.to_csv("/content/drive/MyDrive/pfas_non_iso_languages_corrected.csv", index=False)
print(f" Subset saved: {len(df_non_iso)} rows with non-ISO languages (after correction).")

✅ Subset saved: 349 rows with non-ISO languages (after correction).

In [ ]:

df = pd.read_csv("/content/drive/MyDrive/pfas_comments_with_language_corrected.csv")


manual_fixes = {
    6267: "en",
    6387: "en",
    7706: "en",
    8562: "en",
    9391: "en",
    9559: "en"
}

df["language"] = df.apply(
    lambda row: manual_fixes[row["ID"]] if row["ID"] in manual_fixes else row["language"],
    axis=1
)

def clean_language(lang):
    return lang if re.fullmatch(r"[a-z]{2}", str(lang).strip().lower()) else "undetermined"

df["language"] = df["language"].apply(clean_language)


df.to_csv("/content/drive/MyDrive/pfas_comments_with_language_final.csv", index=False)
print(" Manual fixes applied and non-ISO languages replaced with 'undetermined'.")

✅ Manual fixes applied and non-ISO languages replaced with 'undetermined'.

In [ ]:
df["language"].value_counts()

language
en              4399
sv               747
undetermined     343
de                93
un                14
ja                11
it                 9
fr                 8
nl                 7
zh                 4
cs                 2
ru                 1
no                 1
da                 1
es                 1
pl                 1
Name: count, dtype: int64

In [ ]:
df_un = df[df["language"] == "un"].copy()
df_un.to_csv("/content/drive/MyDrive/pfas_language_un_to_review.csv", index=False)
print(" Exported 'un' rows for manual review.")

📁 Exported 'un' rows for manual review.

In [ ]:
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/pfas_comments_with_language_final.csv")


manual_fixes = {
    4943: "en",
    6080: "en",
    6081: "undetermined",
    6625: "en",
    6652: "en",
    6711: "en",
    7098: "undetermined",
    8205: "en",
    8300: "undetermined",
    8555: "en",
    8681: "en",
    8955: "undetermined",
    9128: "de",
    9550: "en"
}


df["language"] = df.apply(
    lambda row: manual_fixes[row["ID"]] if row["ID"] in manual_fixes else row["language"],
    axis=1
)


output_path = "/content/drive/MyDrive/pfas_comments_with_language_final_v2.csv"
df.to_csv(output_path, index=False)
print(f" Manual fixes applied and saved to: {output_path}")

✅ Manual fixes applied and saved to: /content/drive/MyDrive/pfas_comments_with_language_final_v2.csv

In [ ]:
df["language"].value_counts()

language
en              4408
sv               747
undetermined     347
de                94
ja                11
it                 9
fr                 8
nl                 7
zh                 4
cs                 2
ru                 1
no                 1
da                 1
es                 1
pl                 1
Name: count, dtype: int64

In [ ]:
df[df["language"] == "de"]["General Comments"]

54                                                    NaN
58      Sehr geehrte Damen und Herren, bei einem PFAS-...
636                                                   NaN
667     Wir verarbeiten PTFE-Schläuche und haben keine...
722                                                - 4599
                              ...
5526    Wir unterstützen entschieden den Vorschlag des...
5563                                               - 9514
5567    Der gegenwärtige EU PFAS-Verbotsvorschlag besc...
5616                                                  NaN
5634    Würdigung von Werkzeugmaschinen im Annex XV Re...
Name: General Comments, Length: 94, dtype: object

In [ ]:
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/pfas_comments_with_language_final_v2.csv")


more_fixes = {
    3863: "undetermined",
    4068: "en",
    4701: "undetermined",
    8707: "en"
}


df["language"] = df.apply(
    lambda row: more_fixes[row["ID"]] if row["ID"] in more_fixes else row["language"],
    axis=1
)


output_path = "/content/drive/MyDrive/pfas_comments_with_language_final_v3.csv"
df.to_csv(output_path, index=False)
print(f" Final fixes applied and saved to: {output_path}")

✅ Final fixes applied and saved to: /content/drive/MyDrive/pfas_comments_with_language_final_v3.csv

In [ ]:
df["language"].value_counts()

language
en              4410
sv               747
undetermined     349
de                94
ja                10
fr                 8
nl                 7
it                 7
zh                 4
cs                 2
no                 1
da                 1
es                 1
pl                 1
Name: count, dtype: int64

### Merging

In [ ]:

language_file = "/content/drive/MyDrive/pfas_comments_with_language_final_v3.csv"
translations_file = "/content/drive/MyDrive/pfas_comments_translated_subset.csv"

df_language = pd.read_csv(language_file)
df_translated = pd.read_csv(translations_file)


translated_cols = ["ID"] + [col for col in df_translated.columns if col.endswith("_translated")]

df_merged = df_language.merge(df_translated[translated_cols], on="ID", how="left")


output_file = "/content/drive/MyDrive/pfas_comments_final_with_translations.csv"
df_merged.to_csv(output_file, index=False)

print(f" Merged dataset saved as: {output_file}")

✅ Merged dataset saved as: /content/drive/MyDrive/pfas_comments_final_with_translations.csv

In [ ]:
import pandas as pd


merged_path = "/content/drive/MyDrive/pfas_comments_final_with_translations.csv"
df = pd.read_csv(merged_path)


original_cols = ["General Comments"] + [
    f"Answer to specific info request {i}" for i in range(1, 11)
]
translated_cols = [col + "_translated" for col in original_cols]


df_english = df.copy()

for orig, trans in zip(original_cols, translated_cols):
    df_english[orig] = df_english[trans].combine_first(df_english[orig])


df_english = df_english.drop(columns=translated_cols)


output_file = "/content/drive/MyDrive/pfas_comments_all_english.csv"
df_english.to_csv(output_file, index=False)

print(f"All-English dataset saved to: {output_file}")

✅ All-English dataset saved to: /content/drive/MyDrive/pfas_comments_all_english.csv